export const NAVBAR_TITLE = 'NAVBAR_TITLE';

// Localization
export const SET_LANGUAGE = "SET_LANGUAGE";

// AUTH
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

// ADMIN DATA
export const ADMIN_DATA = 'ADMIN_DATA';
export const ADMIN_DATA_SUCCESS = 'ADMIN_DATA_SUCCESS';
export const ADMIN_DATA_FAILURE = 'ADMIN_DATA_FAILURE';
export const ADMIN_DATA_CLEAR = 'ADMIN_DATA_CLEAR';

// DASHBOARD DATA
export const DASHBOARD_DATA = 'DASHBOARD_DATA';
export const DASHBOARD_DATA_SUCCESS = 'DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_FAILURE = 'DASHBOARD_DATA_FAILURE';

// CUSTOMERS
export const GET_CUSTOMERS = 'GET_CUSTOMERS_DATA';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE';

export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS_DATA';
export const GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILURE = 'GET_CUSTOMER_DETAILS_FAILURE';

export const BLOCK_CUSTOMER = 'BLOCK_CUSTOMER';
export const BLOCK_CUSTOMER_SUCCESS = 'BLOCK_CUSTOMER_SUCCESS';
export const BLOCK_CUSTOMER_FAILURE = 'BLOCK_CUSTOMER_FAILURE';

export const GET_CUSTOMER_WARNINGS = 'GET_CUSTOMER_WARNINGS';
export const GET_CUSTOMER_WARNINGS_SUCCESS = 'GET_CUSTOMER_WARNINGS_SUCCESS';
export const GET_CUSTOMER_WARNINGS_FAILURE = 'GET_CUSTOMER_WARNINGS_FAILURE';

export const SET_CUSTOMER_WARNINGS = 'SET_CUSTOMER_WARNINGS';
export const SET_CUSTOMER_WARNINGS_SUCCESS = 'SET_CUSTOMER_WARNINGS_SUCCESS';
export const SET_CUSTOMER_WARNINGS_FAILURE = 'SET_CUSTOMER_WARNINGS_FAILURE';

export const CUSTOMER_PERSONAL_DETAILS = 'CUSTOMER_PERSONAL_DETAILS';
export const ORDER_DETAILS = 'ORDER_DETAILS';

// SUPPLIERS
export const GET_SUPPLIERS = 'GET_SUPPLIERS_DATA';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_FAILURE = 'GET_SUPPLIERS_FAILURE';

export const GET_SUPPLIER_DETAILS = 'GET_SUPPLIER_DETAILS_DATA';
export const GET_SUPPLIER_DETAILS_SUCCESS = 'GET_SUPPLIER_DETAILS_SUCCESS';
export const GET_SUPPLIER_DETAILS_FAILURE = 'GET_SUPPLIER_DETAILS_FAILURE';

export const BLOCK_SUPPLIER = 'BLOCK_SUPPLIER';
export const BLOCK_SUPPLIER_SUCCESS = 'BLOCK_SUPPLIER_SUCCESS';
export const BLOCK_SUPPLIER_FAILURE = 'BLOCK_SUPPLIER_FAILURE';

export const SUPPLIER_PERSONAL_DETAILS = 'SUPPLIER_PERSONAL_DETAILS';

// PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS_DATA';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS_DATA';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAILURE = 'GET_PRODUCT_DETAILS_FAILURE';

export const BLOCK_PRODUCT = 'BLOCK_PRODUCT';
export const BLOCK_PRODUCT_SUCCESS = 'BLOCK_PRODUCT_SUCCESS';
export const BLOCK_PRODUCT_FAILURE = 'BLOCK_PRODUCT_FAILURE';