export const NAVBAR_TITLE = 'NAVBAR_TITLE';

// Localization
export const SET_LANGUAGE = "SET_LANGUAGE";

// AUTH
export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const GET_USER = 'GET_USER'
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const CLEAR_USER = 'CLEAR_USER'

// ADMIN DATA
export const ADMIN_DATA = 'ADMIN_DATA';
export const ADMIN_DATA_SUCCESS = 'ADMIN_DATA_SUCCESS';
export const ADMIN_DATA_FAILURE = 'ADMIN_DATA_FAILURE';
export const ADMIN_DATA_CLEAR = 'ADMIN_DATA_CLEAR';

// DASHBOARD DATA
export const DASHBOARD_DATA = 'DASHBOARD_DATA';
export const DASHBOARD_DATA_SUCCESS = 'DASHBOARD_DATA_SUCCESS';
export const DASHBOARD_DATA_FAILURE = 'DASHBOARD_DATA_FAILURE';

// SUB_ADMINS
export const GET_SUB_ADMINS = 'GET_SUB_ADMINS_DATA';
export const GET_SUB_ADMINS_SUCCESS = 'GET_SUB_ADMINS_SUCCESS';
export const GET_SUB_ADMINS_FAILURE = 'GET_SUB_ADMINS_FAILURE';

export const ADD_SUB_ADMIN = 'ADD_SUB_ADMIN_DATA';
export const ADD_SUB_ADMIN_SUCCESS = 'ADD_SUB_ADMIN_SUCCESS';
export const ADD_SUB_ADMIN_FAILURE = 'ADD_SUB_ADMIN_FAILURE';

export const UPDATE_SUB_ADMIN = 'UPDATE_SUB_ADMIN_DATA';
export const UPDATE_SUB_ADMIN_SUCCESS = 'UPDATE_SUB_ADMIN_SUCCESS';
export const UPDATE_SUB_ADMIN_FAILURE = 'UPDATE_SUB_ADMIN_FAILURE';

export const UPDATE_SUB_ADMIN_PASSWORD = 'UPDATE_SUB_ADMIN_PASSWORD_DATA';
export const UPDATE_SUB_ADMIN_PASSWORD_SUCCESS = 'UPDATE_SUB_ADMIN_PASSWORD_SUCCESS';
export const UPDATE_SUB_ADMIN_PASSWORD_FAILURE = 'UPDATE_SUB_ADMIN_PASSWORD_FAILURE';

export const DELETE_SUB_ADMIN = 'DELETE_SUB_ADMIN_DATA';
export const DELETE_SUB_ADMIN_SUCCESS = 'DELETE_SUB_ADMIN_SUCCESS';
export const DELETE_SUB_ADMIN_FAILURE = 'DELETE_SUB_ADMIN_FAILURE';

export const SET_SUB_ADMIN_STATUS = 'SET_SUB_ADMIN_STATUS';
export const SET_SUB_ADMIN_STATUS_SUCCESS = 'SET_SUB_ADMIN_STATUS_SUCCESS';
export const SET_SUB_ADMIN_STATUS_FAILURE = 'SET_SUB_ADMIN_STATUS_FAILURE';

export const GET_SUB_ADMIN_DETAILS = 'GET_SUB_ADMIN_DETAILS_DATA';
export const GET_SUB_ADMIN_DETAILS_SUCCESS = 'GET_SUB_ADMIN_DETAILS_SUCCESS';
export const GET_SUB_ADMIN_DETAILS_FAILURE = 'GET_SUB_ADMIN_DETAILS_FAILURE';

// CUSTOMERS
export const GET_CUSTOMERS = 'GET_CUSTOMERS_DATA';
export const GET_CUSTOMERS_SUCCESS = 'GET_CUSTOMERS_SUCCESS';
export const GET_CUSTOMERS_FAILURE = 'GET_CUSTOMERS_FAILURE';

export const ADD_CUSTOMER = 'ADD_CUSTOMER_DATA';
export const ADD_CUSTOMER_SUCCESS = 'ADD_CUSTOMER_SUCCESS';
export const ADD_CUSTOMER_FAILURE = 'ADD_CUSTOMER_FAILURE';

export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER_DATA';
export const UPDATE_CUSTOMER_SUCCESS = 'UPDATE_CUSTOMER_SUCCESS';
export const UPDATE_CUSTOMER_FAILURE = 'UPDATE_CUSTOMER_FAILURE';

export const SET_CUSTOMER_STATUS = 'SET_CUSTOMER_STATUS';
export const SET_CUSTOMER_STATUS_SUCCESS = 'SET_CUSTOMER_STATUS_SUCCESS';
export const SET_CUSTOMER_STATUS_FAILURE = 'SET_CUSTOMER_STATUS_FAILURE';

export const GET_CUSTOMER_DETAILS = 'GET_CUSTOMER_DETAILS_DATA';
export const GET_CUSTOMER_DETAILS_SUCCESS = 'GET_CUSTOMER_DETAILS_SUCCESS';
export const GET_CUSTOMER_DETAILS_FAILURE = 'GET_CUSTOMER_DETAILS_FAILURE';

export const ADD_CUSTOMER_CASH = 'ADD_CASH_DATA';
export const ADD_CUSTOMER_CASH_SUCCESS = 'ADD_CUSTOMER_CASH_SUCCESS';
export const ADD_CUSTOMER_CASH_FAILURE = 'ADD_CUSTOMER_CASH_FAILURE';

// CUSTOMER SALE
export const ADD_SALE = 'ADD_SALE_DATA';
export const ADD_SALE_SUCCESS = 'ADD_SALE_SUCCESS';
export const ADD_SALE_FAILURE = 'ADD_SALE_FAILURE';

export const GET_CUSTOMER_TRANSACTIONS = 'GET_TRANSACTIONS_DATA';
export const GET_CUSTOMER_TRANSACTIONS_SUCCESS = 'GET_CUSTOMER_TRANSACTIONS_SUCCESS';
export const GET_CUSTOMER_TRANSACTIONS_FAILURE = 'GET_CUSTOMER_TRANSACTIONS_FAILURE';

// SUPPLIERS
export const GET_SUPPLIERS = 'GET_SUPPLIERS_DATA';
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS';
export const GET_SUPPLIERS_FAILURE = 'GET_SUPPLIERS_FAILURE';

export const ADD_SUPPLIER = 'ADD_SUPPLIER_DATA';
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS';
export const ADD_SUPPLIER_FAILURE = 'ADD_SUPPLIER_FAILURE';

export const UPDATE_SUPPLIER = 'UPDATE_SUPPLIER_DATA';
export const UPDATE_SUPPLIER_SUCCESS = 'UPDATE_SUPPLIER_SUCCESS';
export const UPDATE_SUPPLIER_FAILURE = 'UPDATE_SUPPLIER_FAILURE';

export const SET_SUPPLIER_STATUS = 'SET_SUPPLIER_STATUS';
export const SET_SUPPLIER_STATUS_SUCCESS = 'SET_SUPPLIER_STATUS_SUCCESS';
export const SET_SUPPLIER_STATUS_FAILURE = 'SET_SUPPLIER_STATUS_FAILURE';

export const GET_SUPPLIER_DETAILS = 'GET_SUPPLIER_DETAILS_DATA';
export const GET_SUPPLIER_DETAILS_SUCCESS = 'GET_SUPPLIER_DETAILS_SUCCESS';
export const GET_SUPPLIER_DETAILS_FAILURE = 'GET_SUPPLIER_DETAILS_FAILURE';

export const ADD_SUPPLIER_CASH = 'ADD_SUPPLIER_CASH_DATA';
export const ADD_SUPPLIER_CASH_SUCCESS = 'ADD_SUPPLIER_CASH_SUCCESS';
export const ADD_SUPPLIER_CASH_FAILURE = 'ADD_SUPPLIER_CASH_FAILURE';

// SUPPLIER PURCHASE
export const ADD_PURCHASE = 'ADD_PURCHASE_DATA';
export const ADD_PURCHASE_SUCCESS = 'ADD_PURCHASE_SUCCESS';
export const ADD_PURCHASE_FAILURE = 'ADD_PURCHASE_FAILURE';

export const GET_SUPPLIER_TRANSACTIONS = 'GET_SUPPLIER_TRANSACTIONS_DATA';
export const GET_SUPPLIER_TRANSACTIONS_SUCCESS = 'GET_SUPPLIER_TRANSACTIONS_SUCCESS';
export const GET_SUPPLIER_TRANSACTIONS_FAILURE = 'GET_SUPPLIER_TRANSACTIONS_FAILURE';

// PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS_DATA';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILURE = 'ADD_PRODUCT_FAILURE';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';

export const SET_PRODUCT_STATUS = 'SET_PRODUCT_STATUS';
export const SET_PRODUCT_STATUS_SUCCESS = 'SET_PRODUCT_STATUS_SUCCESS';
export const SET_PRODUCT_STATUS_FAILURE = 'SET_PRODUCT_STATUS_FAILURE';